"""Add relates with post and gps_posts

Revision ID: 9f879836ed9b
Revises: ead116048cb9
Create Date: 2024-07-08 22:10:42.259418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f879836ed9b'
down_revision: Union[str, None] = 'ead116048cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_posts', sa.Column('post_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'gps_posts', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gps_posts', type_='foreignkey')
    op.drop_column('gps_posts', 'post_id')
    # ### end Alembic commands ###
