"""Add event -> files relationship

Revision ID: 10f08dc8d010
Revises: 0510ceddd637
Create Date: 2024-07-07 18:34:14.698299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f08dc8d010'
down_revision: Union[str, None] = '0510ceddd637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_files', sa.Column('event_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'event_files', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_files', type_='foreignkey')
    op.drop_column('event_files', 'event_id')
    # ### end Alembic commands ###
