"""Init DB

Revision ID: 0510ceddd637
Revises: 
Create Date: 2024-07-07 18:31:26.126085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0510ceddd637'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_files',
    sa.Column('splits_path', sa.String(length=200), nullable=False),
    sa.Column('routes_path', sa.String(length=200), nullable=False),
    sa.Column('results_path', sa.String(length=200), nullable=False),
    sa.Column('routes_size', sa.Integer(), nullable=True),
    sa.Column('results_size', sa.Integer(), nullable=True),
    sa.Column('splits_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('title', sa.String(length=100), server_default='', nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('split_link', sa.String(length=200), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_page', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('median_p_bk', sa.Integer(), nullable=False),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('backlog', sa.Integer(), nullable=True),
    sa.Column('points_number', sa.Integer(), nullable=False),
    sa.Column('split_firsts', sa.Integer(), nullable=True),
    sa.Column('gps', sa.Boolean(), nullable=False),
    sa.Column('image_path', sa.String(length=40), nullable=True),
    sa.Column('split', sa.JSON(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('lenght_s', sa.Integer(), nullable=False),
    sa.Column('lenght_p', sa.Integer(), nullable=False),
    sa.Column('climb', sa.Integer(), nullable=True),
    sa.Column('pace', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('gpx_path', sa.String(length=200), nullable=True),
    sa.Column('coord_data', sa.JSON(), nullable=True),
    sa.Column('index', sa.String(length=50), nullable=True),
    sa.Column('body', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', postgresql.BYTEA(), nullable=False),
    sa.Column('access', sa.INTEGER(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email', sa.String(length=40), server_default='', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('posts')
    op.drop_table('events')
    op.drop_table('event_files')
    # ### end Alembic commands ###
