"""Change created_date to date int events table

Revision ID: bdda5df2a60f
Revises: e684554ce0ab
Create Date: 2024-07-08 21:33:40.926690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdda5df2a60f'
down_revision: Union[str, None] = 'e684554ce0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('events', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
