"""Remove unused columns

Revision ID: e684554ce0ab
Revises: bc8c6f7562d9
Create Date: 2024-07-07 23:13:42.788593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e684554ce0ab'
down_revision: Union[str, None] = 'bc8c6f7562d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_files', 'results_size')
    op.drop_column('event_files', 'routes_size')
    op.drop_column('event_files', 'splits_size')
    op.drop_column('events', 'source_page')
    op.drop_column('events', 'rank')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('source_page', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('event_files', sa.Column('splits_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_files', sa.Column('routes_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_files', sa.Column('results_size', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
