"""Off teammates table

Revision ID: 866f156c30db
Revises: 4944d4d3d12d
Create Date: 2024-10-24 00:31:57.068141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '866f156c30db'
down_revision: Union[str, None] = '4944d4d3d12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teammates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teammates',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='teammates_team_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='teammates_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='teammates_pkey')
    )
    # ### end Alembic commands ###
