"""Add owner_id column to teams

Revision ID: 14130ad830f6
Revises: d26bf2f92306
Create Date: 2024-10-08 18:28:50.906323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14130ad830f6'
down_revision: Union[str, None] = 'd26bf2f92306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('owner_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'owner_id')
    # ### end Alembic commands ###
