"""Add teams, team_members, subscriptions, articles

Revision ID: d26bf2f92306
Revises: 0a3e0f054cfe
Create Date: 2024-10-08 17:11:50.053112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd26bf2f92306'
down_revision: Union[str, None] = '0a3e0f054cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('access', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('posts_event_id_fkey', 'posts', type_='foreignkey')
    op.drop_table('events')
    op.add_column('posts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('track_id', sa.UUID(), nullable=True))
    op.alter_column('posts', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('posts', 'created_date')
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.add_column('posts', sa.Column('created_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_event_id_fkey', 'posts', 'events', ['event_id'], ['id'])
    op.alter_column('posts', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('posts', 'track_id')
    op.drop_column('posts', 'created_at')
    op.create_table('events',
    sa.Column('title', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('split_link', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.drop_table('team_members')
    op.drop_table('articles')
    op.drop_table('teams')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
