"""Remove Event Files table

Revision ID: 68bb522a36e6
Revises: dd03bf1f6f18
Create Date: 2024-08-28 10:47:26.016924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68bb522a36e6'
down_revision: Union[str, None] = 'dd03bf1f6f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_files',
    sa.Column('splits_path', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('routes_path', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('results_path', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_files_event_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='event_files_pkey')
    )
    # ### end Alembic commands ###
