"""Move gps-related columns from post to gps_posts

Revision ID: ead116048cb9
Revises: bdda5df2a60f
Create Date: 2024-07-08 21:56:02.250656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ead116048cb9'
down_revision: Union[str, None] = 'bdda5df2a60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gps_posts',
    sa.Column('lenght_s', sa.Integer(), nullable=False),
    sa.Column('lenght_p', sa.Integer(), nullable=False),
    sa.Column('climb', sa.Integer(), nullable=True),
    sa.Column('pace', sa.Integer(), nullable=False),
    sa.Column('gpx_path', sa.String(length=200), nullable=True),
    sa.Column('coord_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('posts', 'pace')
    op.drop_column('posts', 'location')
    op.drop_column('posts', 'climb')
    op.drop_column('posts', 'lenght_p')
    op.drop_column('posts', 'lenght_s')
    op.drop_column('posts', 'gps')
    op.drop_column('posts', 'coord_data')
    op.drop_column('posts', 'value')
    op.drop_column('posts', 'gpx_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('gpx_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('coord_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('gps', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('lenght_s', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('lenght_p', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('climb', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('location', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('pace', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('gps_posts')
    # ### end Alembic commands ###
