"""Remove gps posts table and simplify posts

Revision ID: 0a3e0f054cfe
Revises: 68bb522a36e6
Create Date: 2024-08-28 21:49:08.631302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a3e0f054cfe'
down_revision: Union[str, None] = '68bb522a36e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gps_posts')
    op.drop_column('posts', 'place')
    op.drop_column('posts', 'split')
    op.drop_column('posts', 'split_firsts')
    op.drop_column('posts', 'median_p_bk')
    op.drop_column('posts', 'backlog')
    op.drop_column('posts', 'result')
    op.drop_column('posts', 'index')
    op.drop_column('posts', 'points_number')
    op.drop_column('posts', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_path', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('points_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('index', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('backlog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('median_p_bk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('split_firsts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('split', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('place', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('gps_posts',
    sa.Column('lenght_s', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lenght_p', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('climb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pace', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gpx_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('coord_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='gps_posts_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='gps_posts_pkey')
    )
    # ### end Alembic commands ###
