"""Add user_id to subscription

Revision ID: 346fea4a5d97
Revises: 14130ad830f6
Create Date: 2024-10-08 18:51:50.891954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346fea4a5d97'
down_revision: Union[str, None] = '14130ad830f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'subscription', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'user_id')
    # ### end Alembic commands ###
