"""Add event -> post relationship

Revision ID: 0c6998b4397c
Revises: 10f08dc8d010
Create Date: 2024-07-07 18:37:23.140619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6998b4397c'
down_revision: Union[str, None] = '10f08dc8d010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'posts', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'event_id')
    # ### end Alembic commands ###
