"""Add pair key to team_members

Revision ID: ce25f7f92249
Revises: 531389f85253
Create Date: 2024-10-09 17:26:38.258802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce25f7f92249'
down_revision: Union[str, None] = '531389f85253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_membership', 'team_members', ['user_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_membership', 'team_members', type_='unique')
    # ### end Alembic commands ###
