"""Add user_stats_by_level table 

Revision ID: 2c0606f06ad4
Revises: 384d6d22f59c
Create Date: 2025-04-05 23:11:19.813410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0606f06ad4'
down_revision: Union[str, None] = '384d6d22f59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('silver', sa.Integer(), nullable=False),
    sa.Column('bronze', sa.Integer(), nullable=False),
    sa.Column('average_place', sa.Float(), nullable=False),
    sa.Column('best_place', sa.Integer(), nullable=True),
    sa.Column('total_time', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Integer(), nullable=False),
    sa.Column('average_backlog', sa.Float(), nullable=False),
    sa.Column('average_backlog_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'level', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    # ### end Alembic commands ###
