"""Add runner_id column to posts table

Revision ID: 384d6d22f59c
Revises: 273d804d2859
Create Date: 2025-04-05 10:28:04.065679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384d6d22f59c'
down_revision: Union[str, None] = '273d804d2859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('runner_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'runner_id')
    # ### end Alembic commands ###
