"""Add access column to user

Revision ID: 503429d436e8
Revises: 115f3cacead9
Create Date: 2025-01-03 14:45:30.380841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '503429d436e8'
down_revision: Union[str, None] = '115f3cacead9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access', sa.String(length=10), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access')
    # ### end Alembic commands ###
