"""remove access column from user

Revision ID: b584642a398c
Revises: 503429d436e8
Create Date: 2025-01-07 20:00:54.642287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b584642a398c'
down_revision: Union[str, None] = '503429d436e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access', sa.VARCHAR(length=10), server_default=sa.text("'1'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
