"""remove media column in posts

Revision ID: b8f820074704
Revises: b584642a398c
Create Date: 2025-01-07 20:51:26.340064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f820074704'
down_revision: Union[str, None] = 'b584642a398c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
