"""fix user-post relations

Revision ID: 115f3cacead9
Revises: 37eb2f1e1af7
Create Date: 2025-01-03 14:02:13.698882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115f3cacead9'
down_revision: Union[str, None] = '37eb2f1e1af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
